# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSpacerItem, QStackedWidget, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1675, 1166)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideRight)
        self.flashTab = QWidget()
        self.flashTab.setObjectName(u"flashTab")
        self.verticalLayout = QVBoxLayout(self.flashTab)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.flashButton = QPushButton(self.flashTab)
        self.flashButton.setObjectName(u"flashButton")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flashButton.sizePolicy().hasHeightForWidth())
        self.flashButton.setSizePolicy(sizePolicy)
        self.flashButton.setMinimumSize(QSize(90, 70))

        self.horizontalLayout.addWidget(self.flashButton)

        self.progressBar = QProgressBar(self.flashTab)
        self.progressBar.setObjectName(u"progressBar")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy1)
        self.progressBar.setMinimumSize(QSize(0, 20))
        self.progressBar.setMaximumSize(QSize(16777215, 22))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)

        self.horizontalLayout.addWidget(self.progressBar)

        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)

        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.stepsTable = QTableWidget(self.flashTab)
        if (self.stepsTable.columnCount() < 2):
            self.stepsTable.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.stepsTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.stepsTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.stepsTable.setObjectName(u"stepsTable")

        self.horizontalLayout_2.addWidget(self.stepsTable)

        self.segmentsTable = QTableWidget(self.flashTab)
        if (self.segmentsTable.columnCount() < 6):
            self.segmentsTable.setColumnCount(6)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(1, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(2, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(3, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(4, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(5, __qtablewidgetitem7)
        self.segmentsTable.setObjectName(u"segmentsTable")

        self.horizontalLayout_2.addWidget(self.segmentsTable)

        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)

        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.tabWidget.addTab(self.flashTab, "")
        self.configureTab = QWidget()
        self.configureTab.setObjectName(u"configureTab")
        self.horizontalLayout_3 = QHBoxLayout(self.configureTab)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.navListWidget = QListWidget(self.configureTab)
        QListWidgetItem(self.navListWidget)
        QListWidgetItem(self.navListWidget)
        QListWidgetItem(self.navListWidget)
        QListWidgetItem(self.navListWidget)
        self.navListWidget.setObjectName(u"navListWidget")
        self.navListWidget.setMaximumSize(QSize(200, 16777215))

        self.horizontalLayout_3.addWidget(self.navListWidget)

        self.stackedWidget = QStackedWidget(self.configureTab)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.pageData = QWidget()
        self.pageData.setObjectName(u"pageData")
        self.verticalLayout_3 = QVBoxLayout(self.pageData)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.labelDataTitle = QLabel(self.pageData)
        self.labelDataTitle.setObjectName(u"labelDataTitle")
        self.labelDataTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_3.addWidget(self.labelDataTitle)

        self.labelDatablocks = QLabel(self.pageData)
        self.labelDatablocks.setObjectName(u"labelDatablocks")
        self.labelDatablocks.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_3.addWidget(self.labelDatablocks)

        self.tableWidgetDatablocks = QTableWidget(self.pageData)
        if (self.tableWidgetDatablocks.columnCount() < 5):
            self.tableWidgetDatablocks.setColumnCount(5)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(4, __qtablewidgetitem12)
        self.tableWidgetDatablocks.setObjectName(u"tableWidgetDatablocks")

        self.verticalLayout_3.addWidget(self.tableWidgetDatablocks)

        self.labelAddSetup = QLabel(self.pageData)
        self.labelAddSetup.setObjectName(u"labelAddSetup")
        self.labelAddSetup.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_3.addWidget(self.labelAddSetup)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.labelChecksumMethod = QLabel(self.pageData)
        self.labelChecksumMethod.setObjectName(u"labelChecksumMethod")

        self.horizontalLayout_4.addWidget(self.labelChecksumMethod)

        self.comboBoxChecksum = QComboBox(self.pageData)
        self.comboBoxChecksum.addItem("")
        self.comboBoxChecksum.addItem("")
        self.comboBoxChecksum.setObjectName(u"comboBoxChecksum")

        self.horizontalLayout_4.addWidget(self.comboBoxChecksum)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer)


        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.labelDetails = QLabel(self.pageData)
        self.labelDetails.setObjectName(u"labelDetails")
        self.labelDetails.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_3.addWidget(self.labelDetails)

        self.tableWidgetDetails = QTableWidget(self.pageData)
        if (self.tableWidgetDetails.columnCount() < 3):
            self.tableWidgetDetails.setColumnCount(3)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidgetDetails.setHorizontalHeaderItem(0, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidgetDetails.setHorizontalHeaderItem(1, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidgetDetails.setHorizontalHeaderItem(2, __qtablewidgetitem15)
        if (self.tableWidgetDetails.rowCount() < 8):
            self.tableWidgetDetails.setRowCount(8)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(0, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(1, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(2, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(3, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(4, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(5, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(6, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(7, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(0, 0, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(1, 0, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(2, 0, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(3, 0, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(4, 0, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(5, 0, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(6, 0, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(7, 0, __qtablewidgetitem31)
        self.tableWidgetDetails.setObjectName(u"tableWidgetDetails")
        self.tableWidgetDetails.horizontalHeader().setVisible(False)
        self.tableWidgetDetails.verticalHeader().setVisible(False)

        self.verticalLayout_3.addWidget(self.tableWidgetDetails)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer)

        self.stackedWidget.addWidget(self.pageData)
        self.pageComm = QWidget()
        self.pageComm.setObjectName(u"pageComm")
        self.verticalLayout_comm = QVBoxLayout(self.pageComm)
        self.verticalLayout_comm.setObjectName(u"verticalLayout_comm")
        self.labelCommTitle = QLabel(self.pageComm)
        self.labelCommTitle.setObjectName(u"labelCommTitle")
        self.labelCommTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_comm.addWidget(self.labelCommTitle)

        self.labelHardware = QLabel(self.pageComm)
        self.labelHardware.setObjectName(u"labelHardware")
        self.labelHardware.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelHardware)

        self.comboBoxHardware = QComboBox(self.pageComm)
        self.comboBoxHardware.addItem("")
        self.comboBoxHardware.addItem("")
        self.comboBoxHardware.addItem("")
        self.comboBoxHardware.addItem("")
        self.comboBoxHardware.setObjectName(u"comboBoxHardware")

        self.verticalLayout_comm.addWidget(self.comboBoxHardware)

        self.labelRadarSide = QLabel(self.pageComm)
        self.labelRadarSide.setObjectName(u"labelRadarSide")
        self.labelRadarSide.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelRadarSide)

        self.comboBoxRadarSide = QComboBox(self.pageComm)
        self.comboBoxRadarSide.addItem("")
        self.comboBoxRadarSide.addItem("")
        self.comboBoxRadarSide.setObjectName(u"comboBoxRadarSide")

        self.verticalLayout_comm.addWidget(self.comboBoxRadarSide)

        self.labelLogicalLink = QLabel(self.pageComm)
        self.labelLogicalLink.setObjectName(u"labelLogicalLink")
        self.labelLogicalLink.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelLogicalLink)

        self.comboBoxLogicalLink = QComboBox(self.pageComm)
        self.comboBoxLogicalLink.addItem("")
        self.comboBoxLogicalLink.addItem("")
        self.comboBoxLogicalLink.setObjectName(u"comboBoxLogicalLink")

        self.verticalLayout_comm.addWidget(self.comboBoxLogicalLink)

        self.tableWidgetCommDetails = QTableWidget(self.pageComm)
        if (self.tableWidgetCommDetails.columnCount() < 2):
            self.tableWidgetCommDetails.setColumnCount(2)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableWidgetCommDetails.setHorizontalHeaderItem(0, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableWidgetCommDetails.setHorizontalHeaderItem(1, __qtablewidgetitem33)
        if (self.tableWidgetCommDetails.rowCount() < 7):
            self.tableWidgetCommDetails.setRowCount(7)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(0, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(1, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(2, __qtablewidgetitem36)
        __qtablewidgetitem37 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(3, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(4, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(5, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(6, __qtablewidgetitem40)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(0, 0, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(1, 0, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(2, 0, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(3, 0, __qtablewidgetitem44)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(4, 0, __qtablewidgetitem45)
        __qtablewidgetitem46 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(5, 0, __qtablewidgetitem46)
        __qtablewidgetitem47 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(6, 0, __qtablewidgetitem47)
        __qtablewidgetitem48 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(0, 1, __qtablewidgetitem48)
        __qtablewidgetitem49 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(1, 1, __qtablewidgetitem49)
        __qtablewidgetitem50 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(2, 1, __qtablewidgetitem50)
        __qtablewidgetitem51 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(3, 1, __qtablewidgetitem51)
        __qtablewidgetitem52 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(4, 1, __qtablewidgetitem52)
        __qtablewidgetitem53 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(5, 1, __qtablewidgetitem53)
        __qtablewidgetitem54 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(6, 1, __qtablewidgetitem54)
        self.tableWidgetCommDetails.setObjectName(u"tableWidgetCommDetails")
        self.tableWidgetCommDetails.horizontalHeader().setVisible(False)
        self.tableWidgetCommDetails.verticalHeader().setVisible(False)

        self.verticalLayout_comm.addWidget(self.tableWidgetCommDetails)

        self.labelCustomConfig = QLabel(self.pageComm)
        self.labelCustomConfig.setObjectName(u"labelCustomConfig")
        self.labelCustomConfig.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelCustomConfig)

        self.tableWidgetCustomConfig = QTableWidget(self.pageComm)
        if (self.tableWidgetCustomConfig.columnCount() < 2):
            self.tableWidgetCustomConfig.setColumnCount(2)
        __qtablewidgetitem55 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setHorizontalHeaderItem(0, __qtablewidgetitem55)
        __qtablewidgetitem56 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setHorizontalHeaderItem(1, __qtablewidgetitem56)
        if (self.tableWidgetCustomConfig.rowCount() < 4):
            self.tableWidgetCustomConfig.setRowCount(4)
        __qtablewidgetitem57 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(0, __qtablewidgetitem57)
        __qtablewidgetitem58 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(1, __qtablewidgetitem58)
        __qtablewidgetitem59 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(2, __qtablewidgetitem59)
        __qtablewidgetitem60 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(3, __qtablewidgetitem60)
        __qtablewidgetitem61 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(0, 0, __qtablewidgetitem61)
        __qtablewidgetitem62 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(1, 0, __qtablewidgetitem62)
        __qtablewidgetitem63 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(2, 0, __qtablewidgetitem63)
        __qtablewidgetitem64 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(3, 0, __qtablewidgetitem64)
        __qtablewidgetitem65 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(0, 1, __qtablewidgetitem65)
        __qtablewidgetitem66 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(1, 1, __qtablewidgetitem66)
        __qtablewidgetitem67 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(2, 1, __qtablewidgetitem67)
        __qtablewidgetitem68 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(3, 1, __qtablewidgetitem68)
        self.tableWidgetCustomConfig.setObjectName(u"tableWidgetCustomConfig")
        sizePolicy1.setHeightForWidth(self.tableWidgetCustomConfig.sizePolicy().hasHeightForWidth())
        self.tableWidgetCustomConfig.setSizePolicy(sizePolicy1)
        self.tableWidgetCustomConfig.setMinimumSize(QSize(0, 122))
        self.tableWidgetCustomConfig.setMaximumSize(QSize(16777215, 122))
        self.tableWidgetCustomConfig.horizontalHeader().setVisible(False)
        self.tableWidgetCustomConfig.verticalHeader().setVisible(False)

        self.verticalLayout_comm.addWidget(self.tableWidgetCustomConfig)

        self.verticalSpacer_comm = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_comm.addItem(self.verticalSpacer_comm)

        self.stackedWidget.addWidget(self.pageComm)
        self.pageMisc = QWidget()
        self.pageMisc.setObjectName(u"pageMisc")
        self.verticalLayout_misc = QVBoxLayout(self.pageMisc)
        self.verticalLayout_misc.setObjectName(u"verticalLayout_misc")
        self.labelMiscTitle = QLabel(self.pageMisc)
        self.labelMiscTitle.setObjectName(u"labelMiscTitle")
        self.labelMiscTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_misc.addWidget(self.labelMiscTitle)

        self.labelFlashSequence = QLabel(self.pageMisc)
        self.labelFlashSequence.setObjectName(u"labelFlashSequence")
        self.labelFlashSequence.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_misc.addWidget(self.labelFlashSequence)

        self.comboBoxFlashSequence = QComboBox(self.pageMisc)
        self.comboBoxFlashSequence.addItem("")
        self.comboBoxFlashSequence.addItem("")
        self.comboBoxFlashSequence.setObjectName(u"comboBoxFlashSequence")

        self.verticalLayout_misc.addWidget(self.comboBoxFlashSequence)

        self.labelSecurityDll = QLabel(self.pageMisc)
        self.labelSecurityDll.setObjectName(u"labelSecurityDll")
        self.labelSecurityDll.setStyleSheet(u"background-color: #E0E0E0; padding: 5px; font-weight: bold;")

        self.verticalLayout_misc.addWidget(self.labelSecurityDll)

        self.horizontalLayout_securityDll = QHBoxLayout()
        self.horizontalLayout_securityDll.setObjectName(u"horizontalLayout_securityDll")
        self.lineEditSecurityDll = QLineEdit(self.pageMisc)
        self.lineEditSecurityDll.setObjectName(u"lineEditSecurityDll")
        self.lineEditSecurityDll.setReadOnly(True)

        self.horizontalLayout_securityDll.addWidget(self.lineEditSecurityDll)

        self.buttonBrowseSecurityDll = QPushButton(self.pageMisc)
        self.buttonBrowseSecurityDll.setObjectName(u"buttonBrowseSecurityDll")

        self.horizontalLayout_securityDll.addWidget(self.buttonBrowseSecurityDll)


        self.verticalLayout_misc.addLayout(self.horizontalLayout_securityDll)

        self.verticalSpacer_misc = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_misc.addItem(self.verticalSpacer_misc)

        self.stackedWidget.addWidget(self.pageMisc)
        self.pageCustom = QWidget()
        self.pageCustom.setObjectName(u"pageCustom")
        self.stackedWidget.addWidget(self.pageCustom)

        self.horizontalLayout_3.addWidget(self.stackedWidget)

        self.tabWidget.addTab(self.configureTab, "")

        self.verticalLayout_2.addWidget(self.tabWidget)

        self.outputTabWidget = QTabWidget(self.centralwidget)
        self.outputTabWidget.setObjectName(u"outputTabWidget")
        self.informationTab = QWidget()
        self.informationTab.setObjectName(u"informationTab")
        self.verticalLayout_infoTab = QVBoxLayout(self.informationTab)
        self.verticalLayout_infoTab.setObjectName(u"verticalLayout_infoTab")
        self.informationText = QTextEdit(self.informationTab)
        self.informationText.setObjectName(u"informationText")

        self.verticalLayout_infoTab.addWidget(self.informationText)

        self.outputTabWidget.addTab(self.informationTab, "")
        self.traceTab = QWidget()
        self.traceTab.setObjectName(u"traceTab")
        self.verticalLayout_traceTab = QVBoxLayout(self.traceTab)
        self.verticalLayout_traceTab.setObjectName(u"verticalLayout_traceTab")
        self.traceText = QTextEdit(self.traceTab)
        self.traceText.setObjectName(u"traceText")

        self.verticalLayout_traceTab.addWidget(self.traceText)

        self.outputTabWidget.addTab(self.traceTab, "")

        self.verticalLayout_2.addWidget(self.outputTabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1675, 30))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.navListWidget.currentRowChanged.connect(self.stackedWidget.setCurrentIndex)

        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.outputTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.flashButton.setText(QCoreApplication.translate("MainWindow", u"Flash", None))
        ___qtablewidgetitem = self.stepsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Timestamp", None))
        ___qtablewidgetitem1 = self.stepsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        ___qtablewidgetitem2 = self.segmentsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        ___qtablewidgetitem3 = self.segmentsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Start Address", None))
        ___qtablewidgetitem4 = self.segmentsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Length", None))
        ___qtablewidgetitem5 = self.segmentsTable.horizontalHeaderItem(3)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtablewidgetitem6 = self.segmentsTable.horizontalHeaderItem(4)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Datablock", None))
        ___qtablewidgetitem7 = self.segmentsTable.horizontalHeaderItem(5)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Segment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flashTab), QCoreApplication.translate("MainWindow", u"Flash", None))

        __sortingEnabled = self.navListWidget.isSortingEnabled()
        self.navListWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.navListWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        ___qlistwidgetitem1 = self.navListWidget.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Communication", None))
        ___qlistwidgetitem2 = self.navListWidget.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Miscellaneous", None))
        ___qlistwidgetitem3 = self.navListWidget.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Custom Actions", None))
        self.navListWidget.setSortingEnabled(__sortingEnabled)

        self.labelDataTitle.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.labelDatablocks.setText(QCoreApplication.translate("MainWindow", u"Datablocks", None))
        ___qtablewidgetitem8 = self.tableWidgetDatablocks.horizontalHeaderItem(1)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtablewidgetitem9 = self.tableWidgetDatablocks.horizontalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Datablock", None))
        ___qtablewidgetitem10 = self.tableWidgetDatablocks.horizontalHeaderItem(3)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Checksum", None))
        ___qtablewidgetitem11 = self.tableWidgetDatablocks.horizontalHeaderItem(4)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Signature", None))
        self.labelAddSetup.setText(QCoreApplication.translate("MainWindow", u"Additional Setup", None))
        self.labelChecksumMethod.setText(QCoreApplication.translate("MainWindow", u"Checksum Method:", None))
        self.comboBoxChecksum.setItemText(0, QCoreApplication.translate("MainWindow", u"Pre-Calculation: via file selection", None))
        self.comboBoxChecksum.setItemText(1, QCoreApplication.translate("MainWindow", u"Calculate during flash", None))

        self.labelDetails.setText(QCoreApplication.translate("MainWindow", u"Details", None))
        ___qtablewidgetitem12 = self.tableWidgetDetails.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Property", None))
        ___qtablewidgetitem13 = self.tableWidgetDetails.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        ___qtablewidgetitem14 = self.tableWidgetDetails.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Timestamp", None))
        ___qtablewidgetitem15 = self.tableWidgetDetails.verticalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem16 = self.tableWidgetDetails.verticalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem17 = self.tableWidgetDetails.verticalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"3", None))
        ___qtablewidgetitem18 = self.tableWidgetDetails.verticalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"4", None))
        ___qtablewidgetitem19 = self.tableWidgetDetails.verticalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"5", None))
        ___qtablewidgetitem20 = self.tableWidgetDetails.verticalHeaderItem(5)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"6", None))
        ___qtablewidgetitem21 = self.tableWidgetDetails.verticalHeaderItem(6)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"7", None))
        ___qtablewidgetitem22 = self.tableWidgetDetails.verticalHeaderItem(7)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"8", None))

        __sortingEnabled1 = self.tableWidgetDetails.isSortingEnabled()
        self.tableWidgetDetails.setSortingEnabled(False)
        ___qtablewidgetitem23 = self.tableWidgetDetails.item(0, 0)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"File", None))
        ___qtablewidgetitem24 = self.tableWidgetDetails.item(1, 0)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"Checksum", None))
        ___qtablewidgetitem25 = self.tableWidgetDetails.item(2, 0)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"Signature", None))
        ___qtablewidgetitem26 = self.tableWidgetDetails.item(3, 0)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"Compression Method", None))
        ___qtablewidgetitem27 = self.tableWidgetDetails.item(4, 0)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"Encryption Method", None))
        ___qtablewidgetitem28 = self.tableWidgetDetails.item(5, 0)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"Start Address", None))
        ___qtablewidgetitem29 = self.tableWidgetDetails.item(6, 0)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"Memory Size", None))
        ___qtablewidgetitem30 = self.tableWidgetDetails.item(7, 0)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"Delta Download", None))
        self.tableWidgetDetails.setSortingEnabled(__sortingEnabled1)

        self.labelCommTitle.setText(QCoreApplication.translate("MainWindow", u"Communication", None))
        self.labelHardware.setText(QCoreApplication.translate("MainWindow", u"Hardware configure", None))
        self.comboBoxHardware.setItemText(0, QCoreApplication.translate("MainWindow", u"VN1640A - Channel 1", None))
        self.comboBoxHardware.setItemText(1, QCoreApplication.translate("MainWindow", u"VN1640A - Channel 2", None))
        self.comboBoxHardware.setItemText(2, QCoreApplication.translate("MainWindow", u"VN1640A - Channel 3", None))
        self.comboBoxHardware.setItemText(3, QCoreApplication.translate("MainWindow", u"VN1640A - Channel 4", None))

        self.labelRadarSide.setText(QCoreApplication.translate("MainWindow", u"Radar Side", None))
        self.comboBoxRadarSide.setItemText(0, QCoreApplication.translate("MainWindow", u"Left (Tx 0x77B / Rx 0x78B)", None))
        self.comboBoxRadarSide.setItemText(1, QCoreApplication.translate("MainWindow", u"Right (Tx 0x77A / Rx 0x78A)", None))

        self.labelLogicalLink.setText(QCoreApplication.translate("MainWindow", u"Logical Link", None))
        self.comboBoxLogicalLink.setItemText(0, QCoreApplication.translate("MainWindow", u"CAN", None))
        self.comboBoxLogicalLink.setItemText(1, QCoreApplication.translate("MainWindow", u"CAN FD", None))

        ___qtablewidgetitem31 = self.tableWidgetCommDetails.horizontalHeaderItem(0)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"Property", None))
        ___qtablewidgetitem32 = self.tableWidgetCommDetails.horizontalHeaderItem(1)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        ___qtablewidgetitem33 = self.tableWidgetCommDetails.verticalHeaderItem(0)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem34 = self.tableWidgetCommDetails.verticalHeaderItem(1)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem35 = self.tableWidgetCommDetails.verticalHeaderItem(2)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"3", None))
        ___qtablewidgetitem36 = self.tableWidgetCommDetails.verticalHeaderItem(3)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"4", None))
        ___qtablewidgetitem37 = self.tableWidgetCommDetails.verticalHeaderItem(4)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"5", None))
        ___qtablewidgetitem38 = self.tableWidgetCommDetails.verticalHeaderItem(5)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"6", None))
        ___qtablewidgetitem39 = self.tableWidgetCommDetails.verticalHeaderItem(6)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"7", None))

        __sortingEnabled2 = self.tableWidgetCommDetails.isSortingEnabled()
        self.tableWidgetCommDetails.setSortingEnabled(False)
        ___qtablewidgetitem40 = self.tableWidgetCommDetails.item(0, 0)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"Baudrate", None))
        ___qtablewidgetitem41 = self.tableWidgetCommDetails.item(1, 0)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("MainWindow", u"Addressing Scheme", None))
        ___qtablewidgetitem42 = self.tableWidgetCommDetails.item(2, 0)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("MainWindow", u"Physical CAN ID Type", None))
        ___qtablewidgetitem43 = self.tableWidgetCommDetails.item(3, 0)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("MainWindow", u"Functional CAN ID Type", None))
        ___qtablewidgetitem44 = self.tableWidgetCommDetails.item(4, 0)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("MainWindow", u"Physical Request CAN ID", None))
        ___qtablewidgetitem45 = self.tableWidgetCommDetails.item(5, 0)
        ___qtablewidgetitem45.setText(QCoreApplication.translate("MainWindow", u"Response CAN ID", None))
        ___qtablewidgetitem46 = self.tableWidgetCommDetails.item(6, 0)
        ___qtablewidgetitem46.setText(QCoreApplication.translate("MainWindow", u"Functional Request CAN ID", None))
        ___qtablewidgetitem47 = self.tableWidgetCommDetails.item(0, 1)
        ___qtablewidgetitem47.setText(QCoreApplication.translate("MainWindow", u"500,000 Baud", None))
        ___qtablewidgetitem48 = self.tableWidgetCommDetails.item(1, 1)
        ___qtablewidgetitem48.setText(QCoreApplication.translate("MainWindow", u"Normal", None))
        ___qtablewidgetitem49 = self.tableWidgetCommDetails.item(2, 1)
        ___qtablewidgetitem49.setText(QCoreApplication.translate("MainWindow", u"11-Bit", None))
        ___qtablewidgetitem50 = self.tableWidgetCommDetails.item(3, 1)
        ___qtablewidgetitem50.setText(QCoreApplication.translate("MainWindow", u"11-Bit", None))
        ___qtablewidgetitem51 = self.tableWidgetCommDetails.item(4, 1)
        ___qtablewidgetitem51.setText(QCoreApplication.translate("MainWindow", u"0x778", None))
        ___qtablewidgetitem52 = self.tableWidgetCommDetails.item(5, 1)
        ___qtablewidgetitem52.setText(QCoreApplication.translate("MainWindow", u"0x788", None))
        ___qtablewidgetitem53 = self.tableWidgetCommDetails.item(6, 1)
        ___qtablewidgetitem53.setText(QCoreApplication.translate("MainWindow", u"0x700", None))
        self.tableWidgetCommDetails.setSortingEnabled(__sortingEnabled2)

        self.labelCustomConfig.setText(QCoreApplication.translate("MainWindow", u"Custom Configuration", None))
        ___qtablewidgetitem54 = self.tableWidgetCustomConfig.horizontalHeaderItem(0)
        ___qtablewidgetitem54.setText(QCoreApplication.translate("MainWindow", u"Property", None))
        ___qtablewidgetitem55 = self.tableWidgetCustomConfig.horizontalHeaderItem(1)
        ___qtablewidgetitem55.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        ___qtablewidgetitem56 = self.tableWidgetCustomConfig.verticalHeaderItem(0)
        ___qtablewidgetitem56.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem57 = self.tableWidgetCustomConfig.verticalHeaderItem(1)
        ___qtablewidgetitem57.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem58 = self.tableWidgetCustomConfig.verticalHeaderItem(2)
        ___qtablewidgetitem58.setText(QCoreApplication.translate("MainWindow", u"3", None))
        ___qtablewidgetitem59 = self.tableWidgetCustomConfig.verticalHeaderItem(3)
        ___qtablewidgetitem59.setText(QCoreApplication.translate("MainWindow", u"4", None))

        __sortingEnabled3 = self.tableWidgetCustomConfig.isSortingEnabled()
        self.tableWidgetCustomConfig.setSortingEnabled(False)
        ___qtablewidgetitem60 = self.tableWidgetCustomConfig.item(0, 0)
        ___qtablewidgetitem60.setText(QCoreApplication.translate("MainWindow", u"Erase Timeout", None))
        ___qtablewidgetitem61 = self.tableWidgetCustomConfig.item(1, 0)
        ___qtablewidgetitem61.setText(QCoreApplication.translate("MainWindow", u"Programming delay", None))
        ___qtablewidgetitem62 = self.tableWidgetCustomConfig.item(2, 0)
        ___qtablewidgetitem62.setText(QCoreApplication.translate("MainWindow", u"Post reset delay", None))
        ___qtablewidgetitem63 = self.tableWidgetCustomConfig.item(3, 0)
        ___qtablewidgetitem63.setText(QCoreApplication.translate("MainWindow", u"STmin override", None))
        ___qtablewidgetitem64 = self.tableWidgetCustomConfig.item(0, 1)
        ___qtablewidgetitem64.setText(QCoreApplication.translate("MainWindow", u"120 sec", None))
        ___qtablewidgetitem65 = self.tableWidgetCustomConfig.item(1, 1)
        ___qtablewidgetitem65.setText(QCoreApplication.translate("MainWindow", u"2 sec", None))
        ___qtablewidgetitem66 = self.tableWidgetCustomConfig.item(2, 1)
        ___qtablewidgetitem66.setText(QCoreApplication.translate("MainWindow", u"1 sec", None))
        ___qtablewidgetitem67 = self.tableWidgetCustomConfig.item(3, 1)
        ___qtablewidgetitem67.setText(QCoreApplication.translate("MainWindow", u"50 msec", None))
        self.tableWidgetCustomConfig.setSortingEnabled(__sortingEnabled3)

        self.labelMiscTitle.setText(QCoreApplication.translate("MainWindow", u"Miscellaneous", None))
        self.labelFlashSequence.setText(QCoreApplication.translate("MainWindow", u"Flash Sequence", None))
        self.comboBoxFlashSequence.setItemText(0, QCoreApplication.translate("MainWindow", u"Generic (Default)", None))
        self.comboBoxFlashSequence.setItemText(1, QCoreApplication.translate("MainWindow", u"Suzuki SLP1 (Real Trace)", None))

        self.labelSecurityDll.setText(QCoreApplication.translate("MainWindow", u"Security Access DLL (Optional)", None))
        self.lineEditSecurityDll.setPlaceholderText(QCoreApplication.translate("MainWindow", u"No DLL selected \u2014 using built-in seed/key algorithm", None))
        self.buttonBrowseSecurityDll.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configureTab), QCoreApplication.translate("MainWindow", u"Configure", None))
        self.outputTabWidget.setTabText(self.outputTabWidget.indexOf(self.informationTab), QCoreApplication.translate("MainWindow", u"Information", None))
        self.outputTabWidget.setTabText(self.outputTabWidget.indexOf(self.traceTab), QCoreApplication.translate("MainWindow", u"Trace", None))
    # retranslateUi

