# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QProgressBar, QPushButton, QSizePolicy, QSpacerItem,
    QSpinBox, QStackedWidget, QStatusBar, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 850)
        self.actionLoadFirmware = QAction(MainWindow)
        self.actionLoadFirmware.setObjectName(u"actionLoadFirmware")
        self.actionLoadFromGitLab = QAction(MainWindow)
        self.actionLoadFromGitLab.setObjectName(u"actionLoadFromGitLab")
        self.actionSaveProjectAs = QAction(MainWindow)
        self.actionSaveProjectAs.setObjectName(u"actionSaveProjectAs")
        self.actionOpenProject = QAction(MainWindow)
        self.actionOpenProject.setObjectName(u"actionOpenProject")
        self.actionCloseWindow = QAction(MainWindow)
        self.actionCloseWindow.setObjectName(u"actionCloseWindow")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionFlash = QAction(MainWindow)
        self.actionFlash.setObjectName(u"actionFlash")
        self.actionAbort = QAction(MainWindow)
        self.actionAbort.setObjectName(u"actionAbort")
        self.actionTestConnection = QAction(MainWindow)
        self.actionTestConnection.setObjectName(u"actionTestConnection")
        self.actionExportReport = QAction(MainWindow)
        self.actionExportReport.setObjectName(u"actionExportReport")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionOpenGuideline = QAction(MainWindow)
        self.actionOpenGuideline.setObjectName(u"actionOpenGuideline")
        self.actionExportIssue = QAction(MainWindow)
        self.actionExportIssue.setObjectName(u"actionExportIssue")
        self.actionDarkMode = QAction(MainWindow)
        self.actionDarkMode.setObjectName(u"actionDarkMode")
        self.actionDarkMode.setCheckable(True)
        self.actionResizeDefault = QAction(MainWindow)
        self.actionResizeDefault.setObjectName(u"actionResizeDefault")
        self.actionResizeMedium = QAction(MainWindow)
        self.actionResizeMedium.setObjectName(u"actionResizeMedium")
        self.actionResizeLarge = QAction(MainWindow)
        self.actionResizeLarge.setObjectName(u"actionResizeLarge")
        self.actionMaximizeWindow = QAction(MainWindow)
        self.actionMaximizeWindow.setObjectName(u"actionMaximizeWindow")
        self.actionFullScreen = QAction(MainWindow)
        self.actionFullScreen.setObjectName(u"actionFullScreen")
        self.actionClearRecentFiles = QAction(MainWindow)
        self.actionClearRecentFiles.setObjectName(u"actionClearRecentFiles")
        self.actionClearInformationLog = QAction(MainWindow)
        self.actionClearInformationLog.setObjectName(u"actionClearInformationLog")
        self.actionClearTrace = QAction(MainWindow)
        self.actionClearTrace.setObjectName(u"actionClearTrace")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_root = QVBoxLayout(self.centralwidget)
        self.verticalLayout_root.setObjectName(u"verticalLayout_root")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideRight)
        self.flashTab = QWidget()
        self.flashTab.setObjectName(u"flashTab")
        self.verticalLayout_flashTab = QVBoxLayout(self.flashTab)
        self.verticalLayout_flashTab.setObjectName(u"verticalLayout_flashTab")
        self.horizontalLayout_flashHeader = QHBoxLayout()
        self.horizontalLayout_flashHeader.setObjectName(u"horizontalLayout_flashHeader")
        self.flashButton = QPushButton(self.flashTab)
        self.flashButton.setObjectName(u"flashButton")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flashButton.sizePolicy().hasHeightForWidth())
        self.flashButton.setSizePolicy(sizePolicy)
        self.flashButton.setMinimumSize(QSize(90, 70))

        self.horizontalLayout_flashHeader.addWidget(self.flashButton)

        self.progressBar = QProgressBar(self.flashTab)
        self.progressBar.setObjectName(u"progressBar")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy1)
        self.progressBar.setMinimumSize(QSize(0, 20))
        self.progressBar.setMaximumSize(QSize(16777215, 22))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)

        self.horizontalLayout_flashHeader.addWidget(self.progressBar)

        self.horizontalLayout_flashHeader.setStretch(0, 1)
        self.horizontalLayout_flashHeader.setStretch(1, 10)

        self.verticalLayout_flashTab.addLayout(self.horizontalLayout_flashHeader)

        self.horizontalLayout_flashTables = QHBoxLayout()
        self.horizontalLayout_flashTables.setObjectName(u"horizontalLayout_flashTables")
        self.stepsTable = QTableWidget(self.flashTab)
        if (self.stepsTable.columnCount() < 2):
            self.stepsTable.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.stepsTable.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.stepsTable.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.stepsTable.setObjectName(u"stepsTable")

        self.horizontalLayout_flashTables.addWidget(self.stepsTable)

        self.segmentsTable = QTableWidget(self.flashTab)
        if (self.segmentsTable.columnCount() < 6):
            self.segmentsTable.setColumnCount(6)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(1, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(2, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(3, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(4, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.segmentsTable.setHorizontalHeaderItem(5, __qtablewidgetitem7)
        self.segmentsTable.setObjectName(u"segmentsTable")

        self.horizontalLayout_flashTables.addWidget(self.segmentsTable)

        self.horizontalLayout_flashTables.setStretch(0, 3)
        self.horizontalLayout_flashTables.setStretch(1, 2)

        self.verticalLayout_flashTab.addLayout(self.horizontalLayout_flashTables)

        self.tabWidget.addTab(self.flashTab, "")
        self.configureTab = QWidget()
        self.configureTab.setObjectName(u"configureTab")
        self.horizontalLayout_configureTab = QHBoxLayout(self.configureTab)
        self.horizontalLayout_configureTab.setObjectName(u"horizontalLayout_configureTab")
        self.navListWidget = QListWidget(self.configureTab)
        QListWidgetItem(self.navListWidget)
        QListWidgetItem(self.navListWidget)
        QListWidgetItem(self.navListWidget)
        QListWidgetItem(self.navListWidget)
        self.navListWidget.setObjectName(u"navListWidget")
        self.navListWidget.setMaximumSize(QSize(200, 16777215))

        self.horizontalLayout_configureTab.addWidget(self.navListWidget)

        self.stackedWidget = QStackedWidget(self.configureTab)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.pageData = QWidget()
        self.pageData.setObjectName(u"pageData")
        self.verticalLayout_dataTab = QVBoxLayout(self.pageData)
        self.verticalLayout_dataTab.setObjectName(u"verticalLayout_dataTab")
        self.labelDataTitle = QLabel(self.pageData)
        self.labelDataTitle.setObjectName(u"labelDataTitle")
        self.labelDataTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_dataTab.addWidget(self.labelDataTitle)

        self.labelDatablocks = QLabel(self.pageData)
        self.labelDatablocks.setObjectName(u"labelDatablocks")
        self.labelDatablocks.setProperty(u"sectionHeader", True)
        self.labelDatablocks.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_dataTab.addWidget(self.labelDatablocks)

        self.tableWidgetDatablocks = QTableWidget(self.pageData)
        if (self.tableWidgetDatablocks.columnCount() < 5):
            self.tableWidgetDatablocks.setColumnCount(5)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidgetDatablocks.setHorizontalHeaderItem(4, __qtablewidgetitem12)
        self.tableWidgetDatablocks.setObjectName(u"tableWidgetDatablocks")

        self.verticalLayout_dataTab.addWidget(self.tableWidgetDatablocks)

        self.labelDetails = QLabel(self.pageData)
        self.labelDetails.setObjectName(u"labelDetails")
        self.labelDetails.setProperty(u"sectionHeader", True)
        self.labelDetails.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_dataTab.addWidget(self.labelDetails)

        self.tableWidgetDetails = QTableWidget(self.pageData)
        if (self.tableWidgetDetails.columnCount() < 3):
            self.tableWidgetDetails.setColumnCount(3)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidgetDetails.setHorizontalHeaderItem(0, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidgetDetails.setHorizontalHeaderItem(1, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidgetDetails.setHorizontalHeaderItem(2, __qtablewidgetitem15)
        if (self.tableWidgetDetails.rowCount() < 6):
            self.tableWidgetDetails.setRowCount(6)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(0, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(1, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(2, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(3, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(4, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidgetDetails.setVerticalHeaderItem(5, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(0, 0, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(1, 0, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(2, 0, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(3, 0, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(4, 0, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableWidgetDetails.setItem(5, 0, __qtablewidgetitem27)
        self.tableWidgetDetails.setObjectName(u"tableWidgetDetails")
        self.tableWidgetDetails.horizontalHeader().setVisible(False)
        self.tableWidgetDetails.verticalHeader().setVisible(False)

        self.verticalLayout_dataTab.addWidget(self.tableWidgetDetails)

        self.buttonLoadFromGitLab = QPushButton(self.pageData)
        self.buttonLoadFromGitLab.setObjectName(u"buttonLoadFromGitLab")

        self.verticalLayout_dataTab.addWidget(self.buttonLoadFromGitLab)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_dataTab.addItem(self.verticalSpacer)

        self.stackedWidget.addWidget(self.pageData)
        self.pageComm = QWidget()
        self.pageComm.setObjectName(u"pageComm")
        self.verticalLayout_comm = QVBoxLayout(self.pageComm)
        self.verticalLayout_comm.setObjectName(u"verticalLayout_comm")
        self.labelCommTitle = QLabel(self.pageComm)
        self.labelCommTitle.setObjectName(u"labelCommTitle")
        self.labelCommTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_comm.addWidget(self.labelCommTitle)

        self.labelHardware = QLabel(self.pageComm)
        self.labelHardware.setObjectName(u"labelHardware")
        self.labelHardware.setProperty(u"sectionHeader", True)
        self.labelHardware.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelHardware)

        self.horizontalLayout_hardware = QHBoxLayout()
        self.horizontalLayout_hardware.setObjectName(u"horizontalLayout_hardware")
        self.comboBoxHardware = QComboBox(self.pageComm)
        self.comboBoxHardware.setObjectName(u"comboBoxHardware")

        self.horizontalLayout_hardware.addWidget(self.comboBoxHardware)

        self.buttonTestConnectionHardware = QPushButton(self.pageComm)
        self.buttonTestConnectionHardware.setObjectName(u"buttonTestConnectionHardware")

        self.horizontalLayout_hardware.addWidget(self.buttonTestConnectionHardware)

        self.buttonRefreshHardware = QPushButton(self.pageComm)
        self.buttonRefreshHardware.setObjectName(u"buttonRefreshHardware")

        self.horizontalLayout_hardware.addWidget(self.buttonRefreshHardware)


        self.verticalLayout_comm.addLayout(self.horizontalLayout_hardware)

        self.labelRadarSide = QLabel(self.pageComm)
        self.labelRadarSide.setObjectName(u"labelRadarSide")
        self.labelRadarSide.setProperty(u"sectionHeader", True)
        self.labelRadarSide.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelRadarSide)

        self.comboBoxRadarSide = QComboBox(self.pageComm)
        self.comboBoxRadarSide.addItem("")
        self.comboBoxRadarSide.addItem("")
        self.comboBoxRadarSide.setObjectName(u"comboBoxRadarSide")

        self.verticalLayout_comm.addWidget(self.comboBoxRadarSide)

        self.labelLogicalLink = QLabel(self.pageComm)
        self.labelLogicalLink.setObjectName(u"labelLogicalLink")
        self.labelLogicalLink.setProperty(u"sectionHeader", True)
        self.labelLogicalLink.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_comm.addWidget(self.labelLogicalLink)

        self.comboBoxLogicalLink = QComboBox(self.pageComm)
        self.comboBoxLogicalLink.addItem("")
        self.comboBoxLogicalLink.addItem("")
        self.comboBoxLogicalLink.setObjectName(u"comboBoxLogicalLink")

        self.verticalLayout_comm.addWidget(self.comboBoxLogicalLink)

        self.tableWidgetCommDetails = QTableWidget(self.pageComm)
        if (self.tableWidgetCommDetails.columnCount() < 2):
            self.tableWidgetCommDetails.setColumnCount(2)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableWidgetCommDetails.setHorizontalHeaderItem(0, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableWidgetCommDetails.setHorizontalHeaderItem(1, __qtablewidgetitem29)
        if (self.tableWidgetCommDetails.rowCount() < 7):
            self.tableWidgetCommDetails.setRowCount(7)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(0, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(1, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(2, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(3, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(4, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(5, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.tableWidgetCommDetails.setVerticalHeaderItem(6, __qtablewidgetitem36)
        __qtablewidgetitem37 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(0, 0, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(1, 0, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(2, 0, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(3, 0, __qtablewidgetitem40)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(4, 0, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(5, 0, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(6, 0, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(0, 1, __qtablewidgetitem44)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(1, 1, __qtablewidgetitem45)
        __qtablewidgetitem46 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(2, 1, __qtablewidgetitem46)
        __qtablewidgetitem47 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(3, 1, __qtablewidgetitem47)
        __qtablewidgetitem48 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(4, 1, __qtablewidgetitem48)
        __qtablewidgetitem49 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(5, 1, __qtablewidgetitem49)
        __qtablewidgetitem50 = QTableWidgetItem()
        self.tableWidgetCommDetails.setItem(6, 1, __qtablewidgetitem50)
        self.tableWidgetCommDetails.setObjectName(u"tableWidgetCommDetails")
        self.tableWidgetCommDetails.horizontalHeader().setVisible(False)
        self.tableWidgetCommDetails.verticalHeader().setVisible(False)

        self.verticalLayout_comm.addWidget(self.tableWidgetCommDetails)

        self.verticalSpacer_comm = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_comm.addItem(self.verticalSpacer_comm)

        self.stackedWidget.addWidget(self.pageComm)
        self.pageMisc = QWidget()
        self.pageMisc.setObjectName(u"pageMisc")
        self.verticalLayout_misc = QVBoxLayout(self.pageMisc)
        self.verticalLayout_misc.setObjectName(u"verticalLayout_misc")
        self.labelMiscTitle = QLabel(self.pageMisc)
        self.labelMiscTitle.setObjectName(u"labelMiscTitle")
        self.labelMiscTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_misc.addWidget(self.labelMiscTitle)

        self.labelFlashSequence = QLabel(self.pageMisc)
        self.labelFlashSequence.setObjectName(u"labelFlashSequence")
        self.labelFlashSequence.setProperty(u"sectionHeader", True)
        self.labelFlashSequence.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_misc.addWidget(self.labelFlashSequence)

        self.comboBoxFlashSequence = QComboBox(self.pageMisc)
        self.comboBoxFlashSequence.addItem("")
        self.comboBoxFlashSequence.addItem("")
        self.comboBoxFlashSequence.setObjectName(u"comboBoxFlashSequence")

        self.verticalLayout_misc.addWidget(self.comboBoxFlashSequence)

        self.labelSecurityDll = QLabel(self.pageMisc)
        self.labelSecurityDll.setObjectName(u"labelSecurityDll")
        self.labelSecurityDll.setProperty(u"sectionHeader", True)
        self.labelSecurityDll.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_misc.addWidget(self.labelSecurityDll)

        self.horizontalLayout_securityDll = QHBoxLayout()
        self.horizontalLayout_securityDll.setObjectName(u"horizontalLayout_securityDll")
        self.lineEditSecurityDll = QLineEdit(self.pageMisc)
        self.lineEditSecurityDll.setObjectName(u"lineEditSecurityDll")
        self.lineEditSecurityDll.setReadOnly(True)

        self.horizontalLayout_securityDll.addWidget(self.lineEditSecurityDll)

        self.buttonBrowseSecurityDll = QPushButton(self.pageMisc)
        self.buttonBrowseSecurityDll.setObjectName(u"buttonBrowseSecurityDll")

        self.horizontalLayout_securityDll.addWidget(self.buttonBrowseSecurityDll)


        self.verticalLayout_misc.addLayout(self.horizontalLayout_securityDll)

        self.labelFingerprint = QLabel(self.pageMisc)
        self.labelFingerprint.setObjectName(u"labelFingerprint")
        self.labelFingerprint.setProperty(u"sectionHeader", True)
        self.labelFingerprint.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_misc.addWidget(self.labelFingerprint)

        self.horizontalLayout_testerSerialNumber = QHBoxLayout()
        self.horizontalLayout_testerSerialNumber.setObjectName(u"horizontalLayout_testerSerialNumber")
        self.labelTesterSerialNumber = QLabel(self.pageMisc)
        self.labelTesterSerialNumber.setObjectName(u"labelTesterSerialNumber")

        self.horizontalLayout_testerSerialNumber.addWidget(self.labelTesterSerialNumber)

        self.lineEditTesterSerialNumber = QLineEdit(self.pageMisc)
        self.lineEditTesterSerialNumber.setObjectName(u"lineEditTesterSerialNumber")

        self.horizontalLayout_testerSerialNumber.addWidget(self.lineEditTesterSerialNumber)


        self.verticalLayout_misc.addLayout(self.horizontalLayout_testerSerialNumber)

        self.verticalSpacer_misc = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_misc.addItem(self.verticalSpacer_misc)

        self.stackedWidget.addWidget(self.pageMisc)
        self.pageCustom = QWidget()
        self.pageCustom.setObjectName(u"pageCustom")
        self.verticalLayout_custom = QVBoxLayout(self.pageCustom)
        self.verticalLayout_custom.setObjectName(u"verticalLayout_custom")
        self.labelCustomTitle = QLabel(self.pageCustom)
        self.labelCustomTitle.setObjectName(u"labelCustomTitle")
        self.labelCustomTitle.setStyleSheet(u"color: #2b579a; font-size: 20px;")

        self.verticalLayout_custom.addWidget(self.labelCustomTitle)

        self.labelCustomConfig = QLabel(self.pageCustom)
        self.labelCustomConfig.setObjectName(u"labelCustomConfig")
        self.labelCustomConfig.setProperty(u"sectionHeader", True)
        self.labelCustomConfig.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_custom.addWidget(self.labelCustomConfig)

        self.tableWidgetCustomConfig = QTableWidget(self.pageCustom)
        if (self.tableWidgetCustomConfig.columnCount() < 2):
            self.tableWidgetCustomConfig.setColumnCount(2)
        __qtablewidgetitem51 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setHorizontalHeaderItem(0, __qtablewidgetitem51)
        __qtablewidgetitem52 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setHorizontalHeaderItem(1, __qtablewidgetitem52)
        if (self.tableWidgetCustomConfig.rowCount() < 4):
            self.tableWidgetCustomConfig.setRowCount(4)
        __qtablewidgetitem53 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(0, __qtablewidgetitem53)
        __qtablewidgetitem54 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(1, __qtablewidgetitem54)
        __qtablewidgetitem55 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(2, __qtablewidgetitem55)
        __qtablewidgetitem56 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setVerticalHeaderItem(3, __qtablewidgetitem56)
        __qtablewidgetitem57 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(0, 0, __qtablewidgetitem57)
        __qtablewidgetitem58 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(1, 0, __qtablewidgetitem58)
        __qtablewidgetitem59 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(2, 0, __qtablewidgetitem59)
        __qtablewidgetitem60 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(3, 0, __qtablewidgetitem60)
        __qtablewidgetitem61 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(0, 1, __qtablewidgetitem61)
        __qtablewidgetitem62 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(1, 1, __qtablewidgetitem62)
        __qtablewidgetitem63 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(2, 1, __qtablewidgetitem63)
        __qtablewidgetitem64 = QTableWidgetItem()
        self.tableWidgetCustomConfig.setItem(3, 1, __qtablewidgetitem64)
        self.tableWidgetCustomConfig.setObjectName(u"tableWidgetCustomConfig")
        sizePolicy1.setHeightForWidth(self.tableWidgetCustomConfig.sizePolicy().hasHeightForWidth())
        self.tableWidgetCustomConfig.setSizePolicy(sizePolicy1)
        self.tableWidgetCustomConfig.setMinimumSize(QSize(0, 122))
        self.tableWidgetCustomConfig.setMaximumSize(QSize(16777215, 122))
        self.tableWidgetCustomConfig.horizontalHeader().setVisible(False)
        self.tableWidgetCustomConfig.verticalHeader().setVisible(False)

        self.verticalLayout_custom.addWidget(self.tableWidgetCustomConfig)

        self.labelStressTest = QLabel(self.pageCustom)
        self.labelStressTest.setObjectName(u"labelStressTest")
        self.labelStressTest.setProperty(u"sectionHeader", True)
        self.labelStressTest.setStyleSheet(u"padding: 5px; font-weight: bold;")

        self.verticalLayout_custom.addWidget(self.labelStressTest)

        self.horizontalLayout_stressTest = QHBoxLayout()
        self.horizontalLayout_stressTest.setObjectName(u"horizontalLayout_stressTest")
        self.labelStressTestCount = QLabel(self.pageCustom)
        self.labelStressTestCount.setObjectName(u"labelStressTestCount")

        self.horizontalLayout_stressTest.addWidget(self.labelStressTestCount)

        self.spinBoxStressTestCount = QSpinBox(self.pageCustom)
        self.spinBoxStressTestCount.setObjectName(u"spinBoxStressTestCount")
        self.spinBoxStressTestCount.setMinimum(1)
        self.spinBoxStressTestCount.setMaximum(9999)
        self.spinBoxStressTestCount.setValue(1)

        self.horizontalLayout_stressTest.addWidget(self.spinBoxStressTestCount)

        self.buttonStressTestStart = QPushButton(self.pageCustom)
        self.buttonStressTestStart.setObjectName(u"buttonStressTestStart")

        self.horizontalLayout_stressTest.addWidget(self.buttonStressTestStart)


        self.verticalLayout_custom.addLayout(self.horizontalLayout_stressTest)

        self.labelStressTestStatus = QLabel(self.pageCustom)
        self.labelStressTestStatus.setObjectName(u"labelStressTestStatus")

        self.verticalLayout_custom.addWidget(self.labelStressTestStatus)

        self.verticalSpacer_custom = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_custom.addItem(self.verticalSpacer_custom)

        self.stackedWidget.addWidget(self.pageCustom)

        self.horizontalLayout_configureTab.addWidget(self.stackedWidget)

        self.tabWidget.addTab(self.configureTab, "")

        self.verticalLayout_root.addWidget(self.tabWidget)

        self.outputTabWidget = QTabWidget(self.centralwidget)
        self.outputTabWidget.setObjectName(u"outputTabWidget")
        self.informationTab = QWidget()
        self.informationTab.setObjectName(u"informationTab")
        self.verticalLayout_infoTab = QVBoxLayout(self.informationTab)
        self.verticalLayout_infoTab.setObjectName(u"verticalLayout_infoTab")
        self.informationText = QTextEdit(self.informationTab)
        self.informationText.setObjectName(u"informationText")

        self.verticalLayout_infoTab.addWidget(self.informationText)

        self.outputTabWidget.addTab(self.informationTab, "")
        self.traceTab = QWidget()
        self.traceTab.setObjectName(u"traceTab")
        self.verticalLayout_traceTab = QVBoxLayout(self.traceTab)
        self.verticalLayout_traceTab.setObjectName(u"verticalLayout_traceTab")
        self.traceTable = QTableWidget(self.traceTab)
        if (self.traceTable.columnCount() < 6):
            self.traceTable.setColumnCount(6)
        __qtablewidgetitem65 = QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(0, __qtablewidgetitem65)
        __qtablewidgetitem66 = QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(1, __qtablewidgetitem66)
        __qtablewidgetitem67 = QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(2, __qtablewidgetitem67)
        __qtablewidgetitem68 = QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(3, __qtablewidgetitem68)
        __qtablewidgetitem69 = QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(4, __qtablewidgetitem69)
        __qtablewidgetitem70 = QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(5, __qtablewidgetitem70)
        self.traceTable.setObjectName(u"traceTable")
        self.traceTable.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.traceTable.setAlternatingRowColors(True)
        self.traceTable.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)

        self.verticalLayout_traceTab.addWidget(self.traceTable)

        self.outputTabWidget.addTab(self.traceTab, "")

        self.verticalLayout_root.addWidget(self.outputTabWidget)

        self.verticalLayout_root.setStretch(0, 3)
        self.verticalLayout_root.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1675, 30))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecentFiles = QMenu(self.menuFile)
        self.menuRecentFiles.setObjectName(u"menuRecentFiles")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuResizeWindow = QMenu(self.menuView)
        self.menuResizeWindow.setObjectName(u"menuResizeWindow")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionLoadFirmware)
        self.menuFile.addAction(self.actionLoadFromGitLab)
        self.menuFile.addAction(self.menuRecentFiles.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSaveProjectAs)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCloseWindow)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionClearInformationLog)
        self.menuEdit.addAction(self.actionClearTrace)
        self.menuView.addAction(self.actionDarkMode)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuResizeWindow.menuAction())
        self.menuResizeWindow.addAction(self.actionResizeDefault)
        self.menuResizeWindow.addAction(self.actionResizeMedium)
        self.menuResizeWindow.addAction(self.actionResizeLarge)
        self.menuResizeWindow.addSeparator()
        self.menuResizeWindow.addAction(self.actionMaximizeWindow)
        self.menuResizeWindow.addAction(self.actionFullScreen)
        self.menuTools.addAction(self.actionFlash)
        self.menuTools.addAction(self.actionAbort)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionTestConnection)
        self.menuTools.addAction(self.actionExportReport)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionOpenGuideline)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionExportIssue)

        self.retranslateUi(MainWindow)
        self.navListWidget.currentRowChanged.connect(self.stackedWidget.setCurrentIndex)

        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.outputTabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionLoadFirmware.setText(QCoreApplication.translate("MainWindow", u"Load Firmware...", None))
        self.actionLoadFromGitLab.setText(QCoreApplication.translate("MainWindow", u"Load from GitLab...", None))
        self.actionSaveProjectAs.setText(QCoreApplication.translate("MainWindow", u"Save Project As...", None))
        self.actionOpenProject.setText(QCoreApplication.translate("MainWindow", u"Open Project...", None))
        self.actionCloseWindow.setText(QCoreApplication.translate("MainWindow", u"Close Window", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionFlash.setText(QCoreApplication.translate("MainWindow", u"Flash", None))
        self.actionAbort.setText(QCoreApplication.translate("MainWindow", u"Abort", None))
        self.actionTestConnection.setText(QCoreApplication.translate("MainWindow", u"Test Connection...", None))
        self.actionExportReport.setText(QCoreApplication.translate("MainWindow", u"Export Report...", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About SFlash", None))
        self.actionOpenGuideline.setText(QCoreApplication.translate("MainWindow", u"Open Guideline", None))
        self.actionExportIssue.setText(QCoreApplication.translate("MainWindow", u"Export Issue...", None))
        self.actionDarkMode.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.actionResizeDefault.setText(QCoreApplication.translate("MainWindow", u"Default (1100 \u00d7 850)", None))
        self.actionResizeMedium.setText(QCoreApplication.translate("MainWindow", u"Medium (1366 \u00d7 768)", None))
        self.actionResizeLarge.setText(QCoreApplication.translate("MainWindow", u"Large (1920 \u00d7 1080)", None))
        self.actionMaximizeWindow.setText(QCoreApplication.translate("MainWindow", u"Maximize Window", None))
        self.actionFullScreen.setText(QCoreApplication.translate("MainWindow", u"Full Screen", None))
        self.actionClearRecentFiles.setText(QCoreApplication.translate("MainWindow", u"Clear Recent Files", None))
        self.actionClearInformationLog.setText(QCoreApplication.translate("MainWindow", u"Clear Information Log", None))
        self.actionClearTrace.setText(QCoreApplication.translate("MainWindow", u"Clear Trace Table", None))
        self.flashButton.setText(QCoreApplication.translate("MainWindow", u"Flash", None))
        ___qtablewidgetitem = self.stepsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Timestamp", None))
        ___qtablewidgetitem1 = self.stepsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        ___qtablewidgetitem2 = self.segmentsTable.horizontalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        ___qtablewidgetitem3 = self.segmentsTable.horizontalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Start Address", None))
        ___qtablewidgetitem4 = self.segmentsTable.horizontalHeaderItem(2)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Length", None))
        ___qtablewidgetitem5 = self.segmentsTable.horizontalHeaderItem(3)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtablewidgetitem6 = self.segmentsTable.horizontalHeaderItem(4)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Datablock", None))
        ___qtablewidgetitem7 = self.segmentsTable.horizontalHeaderItem(5)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Segment", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flashTab), QCoreApplication.translate("MainWindow", u"Flash", None))

        __sortingEnabled = self.navListWidget.isSortingEnabled()
        self.navListWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.navListWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        ___qlistwidgetitem1 = self.navListWidget.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Communication", None))
        ___qlistwidgetitem2 = self.navListWidget.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Miscellaneous", None))
        ___qlistwidgetitem3 = self.navListWidget.item(3)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Custom Actions", None))
        self.navListWidget.setSortingEnabled(__sortingEnabled)

        self.labelDataTitle.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.labelDatablocks.setText(QCoreApplication.translate("MainWindow", u"Datablocks", None))
        ___qtablewidgetitem8 = self.tableWidgetDatablocks.horizontalHeaderItem(1)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        ___qtablewidgetitem9 = self.tableWidgetDatablocks.horizontalHeaderItem(2)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Datablock", None))
        ___qtablewidgetitem10 = self.tableWidgetDatablocks.horizontalHeaderItem(3)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Checksum", None))
        ___qtablewidgetitem11 = self.tableWidgetDatablocks.horizontalHeaderItem(4)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Signature", None))
        self.labelDetails.setText(QCoreApplication.translate("MainWindow", u"Details", None))
        ___qtablewidgetitem12 = self.tableWidgetDetails.horizontalHeaderItem(0)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Property", None))
        ___qtablewidgetitem13 = self.tableWidgetDetails.horizontalHeaderItem(1)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        ___qtablewidgetitem14 = self.tableWidgetDetails.horizontalHeaderItem(2)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Timestamp", None))
        ___qtablewidgetitem15 = self.tableWidgetDetails.verticalHeaderItem(0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem16 = self.tableWidgetDetails.verticalHeaderItem(1)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem17 = self.tableWidgetDetails.verticalHeaderItem(2)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"3", None))
        ___qtablewidgetitem18 = self.tableWidgetDetails.verticalHeaderItem(3)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"4", None))
        ___qtablewidgetitem19 = self.tableWidgetDetails.verticalHeaderItem(4)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"5", None))
        ___qtablewidgetitem20 = self.tableWidgetDetails.verticalHeaderItem(5)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"6", None))

        __sortingEnabled1 = self.tableWidgetDetails.isSortingEnabled()
        self.tableWidgetDetails.setSortingEnabled(False)
        ___qtablewidgetitem21 = self.tableWidgetDetails.item(0, 0)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"File", None))
        ___qtablewidgetitem22 = self.tableWidgetDetails.item(1, 0)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"Checksum", None))
        ___qtablewidgetitem23 = self.tableWidgetDetails.item(2, 0)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"Compression Method", None))
        ___qtablewidgetitem24 = self.tableWidgetDetails.item(3, 0)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"Encryption Method", None))
        ___qtablewidgetitem25 = self.tableWidgetDetails.item(4, 0)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"Start Address", None))
        ___qtablewidgetitem26 = self.tableWidgetDetails.item(5, 0)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"Memory Size", None))
        self.tableWidgetDetails.setSortingEnabled(__sortingEnabled1)

        self.buttonLoadFromGitLab.setText(QCoreApplication.translate("MainWindow", u"Load from GitLab...", None))
        self.labelCommTitle.setText(QCoreApplication.translate("MainWindow", u"Communication", None))
        self.labelHardware.setText(QCoreApplication.translate("MainWindow", u"Hardware configure", None))
        self.buttonTestConnectionHardware.setText(QCoreApplication.translate("MainWindow", u"Test Connection", None))
        self.buttonRefreshHardware.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.labelRadarSide.setText(QCoreApplication.translate("MainWindow", u"Radar Side", None))
        self.comboBoxRadarSide.setItemText(0, QCoreApplication.translate("MainWindow", u"S0 (77B/78B)", None))
        self.comboBoxRadarSide.setItemText(1, QCoreApplication.translate("MainWindow", u"S1 (77A/78A)", None))

        self.labelLogicalLink.setText(QCoreApplication.translate("MainWindow", u"Logical Link", None))
        self.comboBoxLogicalLink.setItemText(0, QCoreApplication.translate("MainWindow", u"CAN", None))
        self.comboBoxLogicalLink.setItemText(1, QCoreApplication.translate("MainWindow", u"CAN FD", None))

        ___qtablewidgetitem27 = self.tableWidgetCommDetails.horizontalHeaderItem(0)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"Property", None))
        ___qtablewidgetitem28 = self.tableWidgetCommDetails.horizontalHeaderItem(1)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        ___qtablewidgetitem29 = self.tableWidgetCommDetails.verticalHeaderItem(0)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem30 = self.tableWidgetCommDetails.verticalHeaderItem(1)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem31 = self.tableWidgetCommDetails.verticalHeaderItem(2)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"3", None))
        ___qtablewidgetitem32 = self.tableWidgetCommDetails.verticalHeaderItem(3)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"4", None))
        ___qtablewidgetitem33 = self.tableWidgetCommDetails.verticalHeaderItem(4)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"5", None))
        ___qtablewidgetitem34 = self.tableWidgetCommDetails.verticalHeaderItem(5)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"6", None))
        ___qtablewidgetitem35 = self.tableWidgetCommDetails.verticalHeaderItem(6)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"7", None))

        __sortingEnabled2 = self.tableWidgetCommDetails.isSortingEnabled()
        self.tableWidgetCommDetails.setSortingEnabled(False)
        ___qtablewidgetitem36 = self.tableWidgetCommDetails.item(0, 0)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"Baudrate", None))
        ___qtablewidgetitem37 = self.tableWidgetCommDetails.item(1, 0)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"Addressing Scheme", None))
        ___qtablewidgetitem38 = self.tableWidgetCommDetails.item(2, 0)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"Physical CAN ID Type", None))
        ___qtablewidgetitem39 = self.tableWidgetCommDetails.item(3, 0)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"Functional CAN ID Type", None))
        ___qtablewidgetitem40 = self.tableWidgetCommDetails.item(4, 0)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"Physical Request CAN ID", None))
        ___qtablewidgetitem41 = self.tableWidgetCommDetails.item(5, 0)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("MainWindow", u"Response CAN ID", None))
        ___qtablewidgetitem42 = self.tableWidgetCommDetails.item(6, 0)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("MainWindow", u"Functional Request CAN ID", None))
        ___qtablewidgetitem43 = self.tableWidgetCommDetails.item(0, 1)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("MainWindow", u"500,000 Baud", None))
        ___qtablewidgetitem44 = self.tableWidgetCommDetails.item(1, 1)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("MainWindow", u"Normal", None))
        ___qtablewidgetitem45 = self.tableWidgetCommDetails.item(2, 1)
        ___qtablewidgetitem45.setText(QCoreApplication.translate("MainWindow", u"11-Bit", None))
        ___qtablewidgetitem46 = self.tableWidgetCommDetails.item(3, 1)
        ___qtablewidgetitem46.setText(QCoreApplication.translate("MainWindow", u"11-Bit", None))
        ___qtablewidgetitem47 = self.tableWidgetCommDetails.item(4, 1)
        ___qtablewidgetitem47.setText(QCoreApplication.translate("MainWindow", u"0x778", None))
        ___qtablewidgetitem48 = self.tableWidgetCommDetails.item(5, 1)
        ___qtablewidgetitem48.setText(QCoreApplication.translate("MainWindow", u"0x788", None))
        ___qtablewidgetitem49 = self.tableWidgetCommDetails.item(6, 1)
        ___qtablewidgetitem49.setText(QCoreApplication.translate("MainWindow", u"0x700", None))
        self.tableWidgetCommDetails.setSortingEnabled(__sortingEnabled2)

        self.labelMiscTitle.setText(QCoreApplication.translate("MainWindow", u"Miscellaneous", None))
        self.labelFlashSequence.setText(QCoreApplication.translate("MainWindow", u"Flash Sequence", None))
        self.comboBoxFlashSequence.setItemText(0, QCoreApplication.translate("MainWindow", u"Suzuki SLP1 (Real Trace) (Default)", None))
        self.comboBoxFlashSequence.setItemText(1, QCoreApplication.translate("MainWindow", u"Generic", None))

        self.labelSecurityDll.setText(QCoreApplication.translate("MainWindow", u"Security Access DLL (Optional)", None))
        self.lineEditSecurityDll.setPlaceholderText(QCoreApplication.translate("MainWindow", u"No DLL selected \u2014 using built-in seed/key algorithm", None))
        self.buttonBrowseSecurityDll.setText(QCoreApplication.translate("MainWindow", u"Browse...", None))
        self.labelFingerprint.setText(QCoreApplication.translate("MainWindow", u"Fingerprint", None))
        self.labelTesterSerialNumber.setText(QCoreApplication.translate("MainWindow", u"Tester Serial Number:", None))
        self.lineEditTesterSerialNumber.setText(QCoreApplication.translate("MainWindow", u"00112233445566778899", None))
#if QT_CONFIG(tooltip)
        self.lineEditTesterSerialNumber.setToolTip(QCoreApplication.translate("MainWindow", u"Hex bytes written to DID 0xF198 (Suzuki SLP1 sequence only)", None))
#endif // QT_CONFIG(tooltip)
        self.labelCustomTitle.setText(QCoreApplication.translate("MainWindow", u"Custom Actions", None))
        self.labelCustomConfig.setText(QCoreApplication.translate("MainWindow", u"Custom Configuration", None))
        ___qtablewidgetitem50 = self.tableWidgetCustomConfig.horizontalHeaderItem(0)
        ___qtablewidgetitem50.setText(QCoreApplication.translate("MainWindow", u"Property", None))
        ___qtablewidgetitem51 = self.tableWidgetCustomConfig.horizontalHeaderItem(1)
        ___qtablewidgetitem51.setText(QCoreApplication.translate("MainWindow", u"Value", None))
        ___qtablewidgetitem52 = self.tableWidgetCustomConfig.verticalHeaderItem(0)
        ___qtablewidgetitem52.setText(QCoreApplication.translate("MainWindow", u"1", None))
        ___qtablewidgetitem53 = self.tableWidgetCustomConfig.verticalHeaderItem(1)
        ___qtablewidgetitem53.setText(QCoreApplication.translate("MainWindow", u"2", None))
        ___qtablewidgetitem54 = self.tableWidgetCustomConfig.verticalHeaderItem(2)
        ___qtablewidgetitem54.setText(QCoreApplication.translate("MainWindow", u"3", None))
        ___qtablewidgetitem55 = self.tableWidgetCustomConfig.verticalHeaderItem(3)
        ___qtablewidgetitem55.setText(QCoreApplication.translate("MainWindow", u"4", None))

        __sortingEnabled3 = self.tableWidgetCustomConfig.isSortingEnabled()
        self.tableWidgetCustomConfig.setSortingEnabled(False)
        ___qtablewidgetitem56 = self.tableWidgetCustomConfig.item(0, 0)
        ___qtablewidgetitem56.setText(QCoreApplication.translate("MainWindow", u"Erase Timeout", None))
        ___qtablewidgetitem57 = self.tableWidgetCustomConfig.item(1, 0)
        ___qtablewidgetitem57.setText(QCoreApplication.translate("MainWindow", u"Programming delay", None))
        ___qtablewidgetitem58 = self.tableWidgetCustomConfig.item(2, 0)
        ___qtablewidgetitem58.setText(QCoreApplication.translate("MainWindow", u"Post reset delay", None))
        ___qtablewidgetitem59 = self.tableWidgetCustomConfig.item(3, 0)
        ___qtablewidgetitem59.setText(QCoreApplication.translate("MainWindow", u"STmin override", None))
        ___qtablewidgetitem60 = self.tableWidgetCustomConfig.item(0, 1)
        ___qtablewidgetitem60.setText(QCoreApplication.translate("MainWindow", u"120 sec", None))
        ___qtablewidgetitem61 = self.tableWidgetCustomConfig.item(1, 1)
        ___qtablewidgetitem61.setText(QCoreApplication.translate("MainWindow", u"2 sec", None))
        ___qtablewidgetitem62 = self.tableWidgetCustomConfig.item(2, 1)
        ___qtablewidgetitem62.setText(QCoreApplication.translate("MainWindow", u"1 sec", None))
        ___qtablewidgetitem63 = self.tableWidgetCustomConfig.item(3, 1)
        ___qtablewidgetitem63.setText(QCoreApplication.translate("MainWindow", u"50 msec", None))
        self.tableWidgetCustomConfig.setSortingEnabled(__sortingEnabled3)

        self.labelStressTest.setText(QCoreApplication.translate("MainWindow", u"Stress Test (testing only \u2014 will be removed later)", None))
        self.labelStressTestCount.setText(QCoreApplication.translate("MainWindow", u"Number of flashes:", None))
        self.buttonStressTestStart.setText(QCoreApplication.translate("MainWindow", u"Start Stress Test", None))
        self.labelStressTestStatus.setText(QCoreApplication.translate("MainWindow", u"Not running.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configureTab), QCoreApplication.translate("MainWindow", u"Configure", None))
        self.outputTabWidget.setTabText(self.outputTabWidget.indexOf(self.informationTab), QCoreApplication.translate("MainWindow", u"Information", None))
        ___qtablewidgetitem64 = self.traceTable.horizontalHeaderItem(0)
        ___qtablewidgetitem64.setText(QCoreApplication.translate("MainWindow", u"Request TimeStamp", None))
        ___qtablewidgetitem65 = self.traceTable.horizontalHeaderItem(1)
        ___qtablewidgetitem65.setText(QCoreApplication.translate("MainWindow", u"Request Target", None))
        ___qtablewidgetitem66 = self.traceTable.horizontalHeaderItem(2)
        ___qtablewidgetitem66.setText(QCoreApplication.translate("MainWindow", u"Request Data", None))
        ___qtablewidgetitem67 = self.traceTable.horizontalHeaderItem(3)
        ___qtablewidgetitem67.setText(QCoreApplication.translate("MainWindow", u"Response TimeStamp", None))
        ___qtablewidgetitem68 = self.traceTable.horizontalHeaderItem(4)
        ___qtablewidgetitem68.setText(QCoreApplication.translate("MainWindow", u"Response Source", None))
        ___qtablewidgetitem69 = self.traceTable.horizontalHeaderItem(5)
        ___qtablewidgetitem69.setText(QCoreApplication.translate("MainWindow", u"Response Data", None))
        self.outputTabWidget.setTabText(self.outputTabWidget.indexOf(self.traceTab), QCoreApplication.translate("MainWindow", u"Trace", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuRecentFiles.setTitle(QCoreApplication.translate("MainWindow", u"Recent Files", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuResizeWindow.setTitle(QCoreApplication.translate("MainWindow", u"Resize Window", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

